server:
  port: 7001
spring:
  profiles:
    active: dev
  application:
    name: getway
logging:
  config: classpath:logback-getway.xml
#
management:
  endpoints:
    web:
      exposure:
        # 端外暴露的端点，使用 "*" 表示暴露所有的端点，bus-refresh 默认是不暴露的
        include: "*"
        exclude: env,beans
#
zuul:
  filter:
    # 过滤器存放的根目录
    root: filter
    # 扫描时间间隔
    interval: 5