CREATE DATABASE hello_test;

USE hello_test;

CREATE TABLE qrtz_job_details(
JOB_NAME VARCHAR(100),
JOB_GROUP
JOB_CLASS_NAME
);

CREATE TABLE qrtz_triggers(
TRIGGER_NAME VARCHAR(100),
JOB_NAME VARCHAR(100),
TRIGGER_GROUP
);

CREATE TABLE qrtz_cron_triggers(
TRIGGER_NAME
TRIGGER_GROUP
CRON_EXPRESSION
TIME_ZONE_ID
);