eureka:
  client:
    service-url:
      defaultZone: http://localhost:8088/eureka/
server:
  port: 8093
spring:
  application:
    name: service-zuul
  servlet:
    multipart:
      enabled: true   # 启用http上传处理
      max-file-size: 100MB # 设置单个文件的最大长度
      max-request-size: 100MB # 设置最大的请求文件的大小
      file-size-threshold: 1MB  # 当上传文件达到1MB的时候进行磁盘写入
      location: /  # 上传的临时目录
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
zuul:
  ribbonIsolationStrategy: THREAD
  routes:
    api-a:
      path: /api-a/**
      serviceId: service-ribbon
    api-b:
      path: /api-b/**
      serviceId: service-feign