#
server:
  port: 6003
spring:
  application:
    name: config-client
  profiles:
    active: dev
#
management:
  endpoints:
    web:
      exposure:
        # 端外暴露的端点，使用 "*" 表示暴露所有的端点，bus-refresh 默认是不暴露的
        include: "bus-refresh"
