spring:
  application:
    name: eureka-server
server:
  port: 1111
#
eureka:
  instance:
    instance-id: aaaa
    hostname: peer1
    metadata-map:
      zone: zone1
  client:
    # \u662F\u5426\u4F7F\u7528\u76F8\u540C\u533A\u57DF Eureka Server
    preferSameZoneEureka: true
    serviceUrl:
      defaultZone: http://peer1:1111/eureka/,http://peer2:2222/eureka/
