server:
  port: 9002
spring:
  application:
    name: consumer2
  sleuth:
    sampler:
      probability: 0.1
#
eureka:
  client:
    service-url:
      defaultZone: http://peer1:1111/eureka/,http://peer2:2222/eureka/
    fetch-registry: true
    registry-fetch-interval-seconds: 30