spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://190.0.1.88:3306/hello_test?useUnicode=true
    username: root
    password: 123456
  quartz:
    properties:
      org:
        quartz:
          scheduler:
            instanceName: DefaultQuartzScheduler
            instanceId: AUTO
          rmi:
            export: false
            proxy: false
          wrapJobExecutionInUserTransaction: false
          jobStore:
            # 默认存储在内存中
            # class: org.quartz.simpl.RAMJobStore
            # 持久化
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            isClustered: true
            clusterCheckinInterval: 10000
            useProperties: false
            misfireThreshold: 5000
            dataSource: qzDS
          threadPool:
            # 实例化ThreadPool时，使用的线程类为 SimpleThreadPool
            class: org.quartz.simpl.SimpleThreadPool
            # threadCount和threadPriority将以setter的形式注入ThreadPool实例
            # 并发个数
            threadCount: 10
            # 优先级
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
    #数据库方式
    job-store-type: jdbc
      #初始化表结构
      #jdbc:
    #initialize-schema: never
mybatis:
  mapper-locations: classpath:com/chenshun/test/mapper/*.xml
