#
server:
  port: 6001
spring:
  application:
    name: config-server
  kafka:
    bootstrap-servers: ci-server:9092,ci-server:9093,ci-server:9094
    producer:
      retries: 0
      # 每次批量发送消息的数量
      batch-size: 16384
      buffer-memory: 33554432
      # 指定消息key和消息体的编解码方式
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: eshop-cache-group
      auto-offset-reset: earliest
      enable-auto-commit: true
      auto-commit-interval: 1s
      # 指定消息key和消息体的编解码方式
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  cloud:
    config:
      server:
        git:
          # Git 仓库地址
          uri: https://github.com/chenshun131/springcloud-config
          # 默认访问分支
          default-label: master
          # 仓库路径下的相对搜索位置，可以配置多个
          search-paths: /demo
          password: 1539831174
          username: k13100689881cs
  security:
    user:
      name: chenshun
      password: 123456
#
eureka:
  client:
    service-url:
      defaultZone: http://peer1:1111/eureka/,http://peer2:2222/eureka/
    fetch-registry: true
    registry-fetch-interval-seconds: 30