server:
  port: 8201
#
spring:
  application:
    name: zipkin-server
  cloud:
    service-registry:
      auto-registration:
        enabled: false
    loadbalancer:
      retry:
        enabled: false
    inetutils:
      useOnlySiteLocalInterfaces: true # 强制仅使用站点本地地址
      ignored-interfaces: # 将要被忽略网络的 Java正则表达式 列表
        # 忽略 docker0接口 和 以"veth"开头的所有接口
        - docker0
        - veth.*
      preferred-networks: # 强制使用 Java正则表达式 列表中指定的网络地址
        - 192.168
        - 10.0
