server:
  port: 9001
# 应用自定义配置 logback
logging:
  config: classpath:logback-consumer.xml
spring:
  profiles:
    active: dev
  application:
    name: consumer1
  zipkin:
    base-url: http://ci-server:9411
  sleuth:
    sampler:
      # 抽样百分比，开发环境可以设置为 1 也就是 100%
      probability: 1
#
eureka:
  instance:
    lease-renewal-interval-in-seconds: 30
  client:
    service-url:
      defaultZone: http://peer1:1111/eureka/,http://peer2:2222/eureka/
    fetch-registry: true
    registry-fetch-interval-seconds: 30
