server:
  port: 8089
spring:
  application:
    name: service-turbine
#
eureka:
  client:
    service-url:
      defaultZone: http://peer1:1111/eureka/,http://peer2:2222/eureka/
    fetch-registry: true
#
turbine:
  aggregator:
    # 指定聚合哪些集群，多个使用","分割，默认为default。可使用http://.../turbine.stream?cluster={clusterConfig之一}访问
    cluster-config: default
  # 需要收集监控信息的服务名，配置 Eureka 中的 serviceId 列表，表明监控哪些服务
  app-config: CONSUMER1,CONSUMER2
  # 指定集群名称，当服务数量非常多的时候，可以启动多个 Turbine 服务来构建不同的聚合集群，而该参数
  # 可以用来区分这些不同的聚合集群，同时该参数值可以再 Hystrix 仪表盘中用来定位不同的聚合集群，只
  # 需在 Hystrix Stream 的 URL 中通过 cluster 参数来指定
  cluster-name-expression: new String("default")
  # 是否让同一主机上的服务通过主机名与端口号的组合来进行区分，默认为true，表示会以 host 以区分不同服务
  # 这会使得在本地调试的时候，本机上的不同服务聚合成一个服务来统计
  combine-host-port: true
  # 和启动类里的 registrationBean.addUrlMappings("/hystrix.stream")一致，原因待探索
  instanceUrlSuffix: /hystrix.stream
#
management:
  endpoints:
    web:
      exposure:
        # 端外暴露的端点，使用 "*" 表示暴露所有的端点，bus-refresh 默认是不暴露的
        include: "*"
        exclude: env,beans    # 排除可能产生冲突的端点
